# SPDX-FileCopyrightText: 2024 Marcel Scherello
# SPDX-License-Identifier: AGPL-3.0-or-later
version = 1
SPDX-PackageName = "sfbridge"
SPDX-PackageSupplier = "Marcel Scherello <sfbridge@scherello.de>"
SPDX-PackageDownloadLocation = "https://github.com/rello/sfbridge"


[[annotations]]
path = "l10n/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Nextcloud translators"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = [".**", "**.md", "**.json", "screenshots/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Marcel Scherello"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["img/app.svg", "img/app-dark.svg", "img/favicon.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Marcel Scherello"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "appinfo/info.xml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Marcel Scherello"
SPDX-License-Identifier = "AGPL-3.0-or-later"